=== yaravaz/1sem/КЯР/12_лабораторная/doc3.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs ="http://www.w3.org/2001/XMLSchema">
<xs:element name="students">
<xs:complexType>
<xs:sequence>
    <xs:element name="example">
    <xs:complexType>
    <xs:sequence>
        <xs:element name="euniversity" type="xs:string"/>
        <xs:element name="ename" type="xs:string"/>
        <xs:element name="esurname" type="xs:string"/>
        <xs:element name="eage" type="xs:string"/>
    </xs:sequence>
    </xs:complexType>
    </xs:element>
    <xs:element name="student">
    <xs:complexType>
    <xs:sequence>
        <xs:element name="university" type="xs:string"/>
        <xs:element name="name" type="xs:string"/>
        <xs:element name="surname" type="xs:string"/>
        <xs:element name="age" type="xs:string"/>
    </xs:sequence>
    </xs:complexType>
    </xs:element>
    <xs:element name="student">
    <xs:complexType>
    <xs:sequence>
        <xs:element name="university" type="xs:string"/>
        <xs:element name="name" type="xs:string"/>
        <xs:element name="surname" type="xs:string"/>
        <xs:element name="age" type="xs:string"/>
    </xs:sequence>
    </xs:complexType>
    </xs:element>
    <xs:element name="student">
    <xs:complexType>
    <xs:sequence>
        <xs:element name="university" type="xs:string"/>
        <xs:element name="name" type="xs:string"/>
        <xs:element name="surname" type="xs:string"/>
        <xs:element name="age" type="xs:string"/>
    </xs:sequence>
    </xs:complexType>
    </xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>

=== yaravaz/1sem/КЯР/12_лабораторная/doc3_xml.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?xml-stylesheet type="text/css" href="forXML.css"?>
<students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="doc3.xsd">
    <example count="3">
        <euniversity>Университет</euniversity>
        <ename>Имя</ename>
        <esurname>Фамилия</esurname>
        <eage>Возраст</eage>
    </example>
    <student>
        <university>БГТУ</university>
        <name>Алина</name>
        <surname>Темникова</surname>
        <age>20</age>
    </student>
    <student>
        <university>БГУИР</university>
        <name>Иван</name>
        <surname>Королов</surname>
        <age>21</age></student>
    <student>
        <university>БГУ</university>
        <name>Мария</name>
        <surname>Приморная</surname>
        <age>19</age></student>
</students>
